import data from './makati-journeys.json';

// Landmark-to-landmark journeys generated by tools/transit/build_journeys.py from OpenStreetMap route data.
// Pure data + lookups: works offline on every platform, no database needed.

export type TransitMode = 'jeepney' | 'e-jeepney' | 'bus' | 'p2p' | 'uv-express';

export interface PlannerPlace {
  id: string;
  name: string;
  /** OpenStreetMap element used for the position, e.g. "way/40190900". */
  osm: string;
  lat: number;
  lon: number;
}

export interface TransitRoute {
  name: string;
  /** Signboard / route code when mapped. */
  ref: string | null;
  mode: TransitMode;
  operator: string | null;
  from: string | null;
  to: string | null;
  note: string | null;
  source: string;
}

export interface StopRef {
  name: string;
  lat: number;
  lon: number;
}

export interface WalkLeg {
  type: 'walk';
  meters: number;
  minutes: number;
  from: StopRef;
  to: StopRef;
  text: string;
}

export interface RideLeg {
  type: 'ride';
  /** Key into the route table (see routeOf). */
  route: string;
  meters: number;
  /** Includes a typical wait. */
  minutes: number;
  board: StopRef;
  alight: StopRef;
  /** [longitude, latitude] pairs of the ridden part of the route; empty when the route has no mapped path. */
  path: [number, number][];
}

export type JourneyLeg = WalkLeg | RideLeg;

export interface JourneyOption {
  kind: 'walk' | 'ride' | 'transfer';
  minutes: number;
  walkMeters: number;
  legs: JourneyLeg[];
}

export type JourneyPlan =
  | { status: 'unknown-place' }
  | { status: 'same-place'; place: PlannerPlace }
  | { status: 'planned'; origin: PlannerPlace; destination: PlannerPlace; straightMeters: number; options: JourneyOption[] };

interface PlannerData {
  generated: string;
  attribution: string;
  method: string;
  places: PlannerPlace[];
  routes: Record<string, TransitRoute>;
  journeys: Record<string, { straightMeters: number; options: JourneyOption[] }>;
}

const planner = data as unknown as PlannerData;

export const TRANSIT_ATTRIBUTION = planner.attribution;
export const TRANSIT_METHOD = planner.method;
/** Date the route data was fetched from OpenStreetMap (YYYY-MM-DD). */
export const TRANSIT_DATA_DATE = planner.generated;
export const PLANNER_PLACES: readonly PlannerPlace[] = planner.places;
/** Distinct jeepney, bus and P2P routes used by at least one recommendation. */
export const TRANSIT_ROUTE_COUNT = Object.keys(planner.routes).length;

export function placeOf(id: string): PlannerPlace | undefined {
  return planner.places.find((place) => place.id === id);
}

export function routeOf(id: string): TransitRoute {
  const route = planner.routes[id];
  if (!route) throw new Error(`Unknown transit route ${id}.`);
  return route;
}

/** Recommended ways from one supported landmark to another, fastest first. */
export function planJourney(originId: string, destinationId: string): JourneyPlan {
  const origin = placeOf(originId);
  const destination = placeOf(destinationId);
  if (!origin || !destination) return { status: 'unknown-place' };
  if (origin.id === destination.id) return { status: 'same-place', place: origin };
  const journey = planner.journeys[`${origin.id}|${destination.id}`];
  if (!journey) return { status: 'unknown-place' };
  return { status: 'planned', origin, destination, straightMeters: journey.straightMeters, options: journey.options };
}

export const MODE_LABELS: Record<TransitMode, string> = {
  jeepney: 'Jeepney', 'e-jeepney': 'E-jeepney', bus: 'Bus', p2p: 'P2P bus', 'uv-express': 'UV Express',
};

/** One-line summary of an option, e.g. "Jeepney · 23 min · 540 m walk". */
export function summarizeOption(option: JourneyOption): string {
  const rides = option.legs.filter((leg): leg is RideLeg => leg.type === 'ride').map((leg) => MODE_LABELS[routeOf(leg.route).mode]);
  const how = rides.length === 0 ? 'Walk' : rides.join(' + ');
  return `${how} · about ${option.minutes} min · ${formatDistance(option.walkMeters)} walk`;
}

export function formatDistance(meters: number): string {
  return meters >= 1000 ? `${(meters / 1000).toFixed(1)} km` : `${Math.round(meters / 10) * 10} m`;
}
